apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-log-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: event-log-manager
spec:
  replicas: {{.Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: event-log-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-log-manager
    spec:
      affinity: 
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms: 
            - matchExpressions: 
              - key: type
                operator: In
                values:
                - {{ .Values.nodeLabelSelection }}
      containers:
      - name: event-log-manager
        image: "{{ .Values.image.name }}:{{ .Chart.Version}}-{{ .Values.image.env }}"
        ports:
        - containerPort: 3007
        env:
          - name: CONTACT_POINTS
            value: cluster1-dc1-all-pods-service.cass-operator
          - name: LOCAL_DATA_CENTER
            value: dc1
          - name: KEYSPACE
            value: iot
          - name: CONSUMER_GROUP_NAME
            value: PACKET_MANAGER
          - name: TRIGGER_TOPIC_NAME
            value: TELTONIKA_MESSAGE_RECEIVED
        envFrom:
        - configMapRef:
            name: {{ .Values.environmentVariablesFile }}
      imagePullSecrets:
        - name: our-registry  